apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
        - name: udacity-restapi-user
          image: claudioacioli/udacity-restapi-user
          imagePullPolicy: Always
          env:
            - name: POSTGRESS_HOST
              value: "host"
            - name: POSTGRESS_USERNAME
              value: "username"
            - name: POSTGRESS_PASSWORD
              value: "password"
            - name: POSTGRESS_DB
              value: "db"
            - name: JWT_SECRET
              value: "secret"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
